### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by engineervix** [avendesora/django-bible#2]
Howdy @avendesora, thanks for this Django package, which seems to be interesting. I wanted to develop something similar, but decided to search the cheese shop first, just in case someone had already written something, and that's how I stumbled upon *django-bible*.

However, *django-bible* lacks the requisite documentation to enable a developer to quickly integrate the package into their project. The README only focuses on how to install it, and which python versions are supported. Could you update it to include: 

- how to actually use it in a Django project
- features (available classes, methods, options, etc)
- caveats or limitations
- supported Django versions

This will be of great benefit to anyone who stumbles upon the package and would want to use it.

I would also be interested in knowing your intended roadmap for the package, and perhaps areas where you would like others to contribute in improving it.

**Comment by avendesora** [comment]
Hi @engineervix, thanks so much for contacting me. It's very encouraging and exciting to see someone else interested in this.

You're absolutely correct about the documentation. I'm working on updating it right now and should have the README updated with the current functionality before the end of my day today.

Once I've finished that I'll reply back here with information about what I would like for this project to become. Assuming there is decent overlap with what you are needing, I'm very open to collaboration.

**Comment by avendesora** [comment]
Hi @engineervix, I have updated the README with documentation of the current functionality and its usage. As far as my intended roadmap, the main outstanding feature for my current needs is the many-to-many relationship mentioned at the end of the README. Included with that would be the ability to search and sort by that relationship.

I would also like to have functionality for displaying passages of Scripture containing more than one verse with proper formatting, but that is mostly dependent on getting that functionality in the related pythonbible library.

Other than that, I'm open to feedback on what features would be useful for others.

**Comment by engineervix** [comment]
Thanks @avendesora for taking the time to update the documentation. Kudos for the commendable job! :clap: I have gone through it and now I have a much better picture of the package. I will explore it further in due course, and will be happy to provide further feedback once I get to use it. Grace and peace.
